// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eetpvdpuxmpfrvlwqkbk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVldHB2ZHB1eG1wZnJ2bHdxa2JrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MDA4MTksImV4cCI6MjA2ODk3NjgxOX0.nrUjlyM0BbV2qy5GQ5glF-EcciUnOSgBkcjMLkqLzk8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});